### ISSUE TITLE
PLEASE change the name

### ISSUE THREAD

**Issue by Sushi123ff** [KevinTyrrell/FishingBot#10]
PLEASE change the name of the window ... the Wow client scans your processes and search bot software. The Name ist very showy :D (sry for my bad englisch ^^)

**Comment by KevinTyrrell** [comment]
The name of the program will not cause a ban. The software never accesses the `WoW.exe` executable so to Warden it appears as a harmless java program. If you can gather evidence that FishingBot lead to a ban then I will investigate but I assure you it cannot happen. The only way you can get banned using FishingBot is if you are behaving suspicious in-game (such as staying in the same spot for a large amount of time).
