### ISSUE TITLE
Program doesn't work well.

### ISSUE THREAD

**Issue by ZhangxiaoHuangfu** [KevinTyrrell/FishingBot#19]
Program can't calibrate as expected. Always move mouse to wrong place.
Any suggestion?

**Comment by KevinTyrrell** [comment]
@ZhangxiaoHuangfu 

FishingBot needs to be able to find this tooltip on your screen.

![](https://i.imgur.com/gvVbmH3.png)

Normally, that tooltip is in the bottom right hand of your screen. If it is not, then you must tell FishingBot where to find that tooltip. 
Right click on the `Calibrate` button and draw a rectangle around the area where the **Fishing Bobber** tooltip appears. Then `/cast Fishing` in-game, immediately click the `Calibrate` button, then hover your mouse over the Fishing Bobber in the water. It should be able to calibrate successfully. If not, please take a screenshot of your UI while fishing and post it here.

**Comment by ZhangxiaoHuangfu** [comment]
Thanks for your reply.
The program has been working right~~
