### ISSUE TITLE
Calibration is not working

### ISSUE THREAD

**Issue by Gabology** [KevinTyrrell/FishingBot#2]
Just tried the latest release on 1.12.1 and after pressing the calibration button and mousing over the bobber it does not seem to calibrate. If I press start after this the program displays the message that it needs to be calibrated.

Doing a manual calibration will trigger similar behavior.

**Comment by KevinTyrrell** [comment]
Hey OverlyExcessive, 

Sorry for missing this report. 
This message means the program could not locate your 'Fishing Bobber' tooltip. This can happen in the following circumstances: 

* Your tooltip is not located where the program expects it to be
* Your tooltip text is not of the standard golden color

You can right click the calibration button and it will show the location of where the program is searching for the tooltip. Can you ensure that it's correct?

Thanks!
