### ISSUE TITLE
Jar file gives an error

### ISSUE THREAD

**Issue by 1mPerec** [KevinTyrrell/FishingBot#24]
java -jar /Users/1mperec/Desktop/fishingBot/src/FishingBot.jar 
Error: Could not find or load main class view.GUI
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by 1mPerec** [comment]
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)

**Comment by 1mPerec** [comment]
doesn't work on mac. Works on my windows thou... so...

**Comment by SvenStahlmann** [comment]
You need oracle java jre 1.8, since it uses javafx which is not bundled into openjdk
