### ISSUE TITLE
classic

### ISSUE THREAD

**Issue by beren12** [KevinTyrrell/FishingBot#31]
Wondering is this works for classic

**Comment by KevinTyrrell** [comment]
> 
> 
> Wondering is this works for classic

Yes. I recommend using old-school water settings in the graphics menu to improve the accuracy of the detection (the splash with the new graphics is very subtle and thus hard for FishingBot to detect).

If you have difficulty running `FishingBot.jar`, you may need to install Java 8. You can find a download location for that [here](https://www.oracle.com/java/technologies/javase-jre8-downloads.html)
